### ISSUE TITLE
Upstream signald binaries requires glibc>=2.29

### ISSUE THREAD

**Issue by MayeulC** [YunoHost-Apps/mautrix_signal_ynh#31]
Upstream now builds native libraries using debian bullseye instead of buster. Bullseye upgrades glibc to `2.29` from `2.28`. Since the rust toolchain is built with that, the binaries need 2.29 as well.

I submitted a patch to upstream to build with buster, let's hope it gets accepted:
* https://gitlab.com/signald/libraries/zkgroup/-/merge_requests/5
* https://gitlab.com/signald/libraries/libsignal-client/-/merge_requests/1

An alternative is to compile from source #9 

Meanwhile, signald versions from about 3 weeks ago and up are unusable. The app will install, but linking a device is not possible:

```
(Me) > link

(Signal bridge bot) > Unhandled error while handling command:
Traceback (most recent call last):
  File "/opt/yunohost/mautrix_signal/lib/python3.7/site-packages/mautrix/bridge/commands/handler.py", line 409, in handle
    await self._run_handler(handler, evt)
  File "/opt/yunohost/mautrix_signal/lib/python3.7/site-packages/mautrix/bridge/commands/handler.py", line 296, in __call__
    return await self._handler(evt)
  File "/opt/yunohost/mautrix_signal/lib/python3.7/site-packages/mautrix_signal/commands/auth.py", line 64, in link
    sess = await evt.bridge.signal.start_link()
  File "/opt/yunohost/mautrix_signal/lib/python3.7/site-packages/mausignald/signald.py", line 112, in start_link
    return LinkSession.deserialize(await self.request_v1("generate_linking_uri"))
  File "/opt/yunohost/mautrix_signal/lib/python3.7/site-packages/mausignald/rpc.py", line 221, in request_v1
    return await self.request(command, expected_response=command, version="v1", **data)
  File "/opt/yunohost/mautrix_signal/lib/python3.7/site-packages/mausignald/rpc.py", line 215, in request
    resp_type, resp_data = await self._raw_request(command, **data)
  File "/opt/yunohost/mautrix_signal/lib/python3.7/site-packages/mausignald/rpc.py", line 212, in _raw_request
    return await asyncio.shield(future)
mausignald.errors.ResponseError: UnsatisfiedLinkError: /tmp/resource7826374141016698858.so: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/resource7826374141016698858.so)

```

**Comment by Gredin67** [comment]
I see 2 options:
- wait for Yunohost 5/bullseye and rather invest time to solve other issues such as #24 #25 
- install glibc to 2.29 from buster-backport with the extra repository helper?

**Comment by alexAubin** [comment]
Ogod yeah I would say let's focus on support for bullseye ... We should release an alpha in the coming weeks / days ... (Also we're jumping to v11 not v5, we're willing to match with debian version for simplicity)

**Comment by MayeulC** [comment]
Upstream reverted to buster in order to fix this: https://gitlab.com/signald/libraries/libsignal-client/-/commit/f0b1c1a348c6d9f7182a11b8e747292fdeca0add

Currently signald requires zkgroup which is still built on bullseye. This will change once the following is merged: https://gitlab.com/signald/signald/-/merge_requests/93
