### ISSUE TITLE
Install has failed

### ISSUE THREAD

**Issue by Thatoo** [YunoHost-Apps/mautrix_signal_ynh#4]
### Describe the bug

Install has failed

### Context

- Hardware: *VPS bought online / Old laptop or computer 
- YunoHost version: 4.2.6.1
- I have access to my server: Through SSH | through the webadmin | direct access via keyboard / screen 
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no

### Steps to reproduce

Launch install through webgui but it failed

### Expected behavior

Installation success

### Logs

https://paste.yunohost.org/raw/ijofuvecac

**Comment by Thatoo** [comment]
I guess the problem is somewhere in here : 

```
2021-07-20 10:20:33,319: DEBUG - + /opt/yunohost/mautrix_signal/bin/pip3 install '/opt/yunohost/mautrix_signal/src/mautrix-signal.tar.gz[metrics,formattednumbers,qrlink]'
2021-07-20 10:20:34,588: DEBUG - Processing /opt/yunohost/mautrix_signal/src/mautrix-signal.tar.gz
2021-07-20 10:20:34,833: DEBUG -     Complete output from command python setup.py egg_info:
2021-07-20 10:20:34,833: DEBUG -     Traceback (most recent call last):
2021-07-20 10:20:34,834: DEBUG -       File "<string>", line 1, in <module>
2021-07-20 10:20:34,834: DEBUG -       File "/tmp/pip-req-build-77fl3lvi/setup.py", line 3, in <module>
2021-07-20 10:20:34,834: DEBUG -         from mautrix_signal.get_version import git_tag, git_revision, version, linkified_version
2021-07-20 10:20:34,834: DEBUG -       File "/tmp/pip-req-build-77fl3lvi/mautrix_signal/get_version.py", line 9, in <module>
2021-07-20 10:20:34,834: DEBUG -         "HOME": os.environ["HOME"],
2021-07-20 10:20:34,834: DEBUG -       File "/usr/lib/python3.7/os.py", line 678, in __getitem__
2021-07-20 10:20:34,834: DEBUG -         raise KeyError(key) from None
2021-07-20 10:20:34,834: DEBUG -     KeyError: 'HOME'
2021-07-20 10:20:34,834: DEBUG - 
2021-07-20 10:20:34,834: DEBUG -     ----------------------------------------
2021-07-20 10:20:34,837: WARNING - Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-77fl3lvi/
2021-07-20 10:20:34,891: DEBUG - + ynh_exit_properly
2021-07-20 10:20:34,891: DEBUG - + local exit_code=1
2021-07-20 10:20:34,891: DEBUG - + rm -rf /var/cache/yunohost/download/
2021-07-20 10:20:34,892: DEBUG - + '[' 1 -eq 0 ']'
2021-07-20 10:20:34,892: DEBUG - + trap '' EXIT
2021-07-20 10:20:34,892: DEBUG - + set +o errexit
2021-07-20 10:20:34,893: DEBUG - + set +o nounset
2021-07-20 10:20:34,893: DEBUG - + sleep 0.5
2021-07-20 10:20:35,393: DEBUG - + type -t ynh_clean_setup
2021-07-20 10:20:35,394: DEBUG - + ynh_clean_setup
2021-07-20 10:20:35,394: DEBUG - + true
2021-07-20 10:20:35,394: DEBUG - + exit 1
2021-07-20 10:20:36,395: ERROR - Impossible d’installer mautrix_signal : Une erreur est survenue dans le script d’installation de l’application
```

**Comment by Thatoo** [comment]
installing it through CLI with the following command
`sudo yunohost app install https://github.com/YunoHost-Apps/mautrix_signal_ynh --debug`
did work.
I could make a room where I invited Signal bridge bot and he joined.
So install is ok!
