### ISSUE TITLE
link and register not working: Authorization failed!

### ISSUE THREAD

**Issue by rosbeef** [YunoHost-Apps/mautrix_signal_ynh#46]
### Describe the bug

link and register not working

### Context

- Hardware: odroid hc1 armhf(v7)
- YunoHost version: 4.3.6.2
- I have access to my server: Through SSH | through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: yes
       - If yes, please explain: inside lxc container
- Using, or trying to install package version/branch: master
- If upgrading, current package version: NA

### Steps to reproduce
link from element

### Expected behavior
link works

### Logs

```
[2022-04-02 19:51:45,127] [[ERROR@mau.commands](mailto:ERROR@mau.commands)[](https://github.com/rosbeef)] Fatal error while waiting for linking to finish
Traceback (most recent call last):
File "/opt/yunohost/mautrix_signal/lib/python3.7/site-packages/mautrix_signal/commands/auth.py", line 80, in link
session_id=sess.session_id, overwrite=True, device_name=device_name
File "/opt/yunohost/mautrix_signal/lib/python3.7/site-packages/mausignald/signald.py", line 165, in finish_link
"finish_link", device_name=device_name, session_id=session_id, overwrite=overwrite
File "/opt/yunohost/mautrix_signal/lib/python3.7/site-packages/mausignald/rpc.py", line 244, in request_v1
return await self._request(command, expected_response=command, version="v1", **data)
File "/opt/yunohost/mautrix_signal/lib/python3.7/site-packages/mausignald/rpc.py", line 238, in _request
resp_type, resp_data = await self._raw_request(command, **data)
File "/opt/yunohost/mautrix_signal/lib/python3.7/site-packages/mausignald/rpc.py", line 235, in _raw_request
return await asyncio.shield(future)
mausignald.errors.ScanTimeoutError: org.whispersystems.signalservice.api.push.exceptions.AuthorizationFailedException: [403] Authorization failed!
```

maybe it's linked with the release and corrected with last release.
https://gitlab.com/signald/signald/-/issues/310

**Comment by Gredin67** [comment]
hopefully solved by #50
