### ISSUE TITLE
registration fail

### ISSUE THREAD

**Issue by rosbeef** [YunoHost-Apps/mautrix_signal_ynh#74]
### Describe the bug

registration fail

### Context

- Hardware: *ordoid hc1*
- YunoHost version: 11.0.10.2
- I have access to my server: *Through SSH | through the webadmin | direct access via keyboard / screen | ...*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no / yes*
  - If yes, please explain: ynh in an lxccontainer
- Using, or trying to install package version/branch: 0.4.2~ynh1

### Steps to reproduce

- type register in the signal brige bot room or direclty wit the signald bash command returns
-> registration fail
### Expected behavior

registration works

### Logs
Traceback (most recent call last):
  File "/opt/yunohost/mautrix_signal/lib/python3.9/site-packages/mautrix/bridge/commands/handler.py", line 491, in handle
    await self._run_handler(handler, evt)
  File "/opt/yunohost/mautrix_signal/lib/python3.9/site-packages/mautrix_signal/commands/auth.py", line 206, in enter_captcha_token
    username = await evt.bridge.signal.register(phone, voice=voice, captcha=captcha)
  File "/opt/yunohost/mautrix_signal/lib/python3.9/site-packages/mausignald/signald.py", line 160, in register
    resp = await self.request_v1("register", account=phone, voice=voice, captcha=captcha)
  File "/opt/yunohost/mautrix_signal/lib/python3.9/site-packages/mausignald/rpc.py", line 244, in request_v1
    return await self._request(command, expected_response=command, version="v1", **data)
  File "/opt/yunohost/mautrix_signal/lib/python3.9/site-packages/mausignald/rpc.py", line 238, in _request
    resp_type, resp_data = await self._raw_request(command, **data)
  File "/opt/yunohost/mautrix_signal/lib/python3.9/site-packages/mausignald/rpc.py", line 235, in _raw_request
    return await asyncio.shield(future)
mausignald.errors.InternalError: error registering with server

**Comment by Thatoo** [comment]
I face a very similar issue issue

[2023-07-08 19:16:11,893] [ERROR@mau.commands] Unhandled error while handling command register +xxxxxxxxxxx from @zzz:mydomain.fr (ref: 1688749722)
Traceback (most recent call last):
  File "/opt/yunohost/mautrix_signal/lib/python3.9/site-packages/mautrix/bridge/commands/handler.py", line 491, in handle
    await self._run_handler(handler, evt)
  File "/opt/yunohost/mautrix_signal/lib/python3.9/site-packages/mautrix/bridge/commands/handler.py", line 340, in __call__
    return await self._handler(evt)
  File "/opt/yunohost/mautrix_signal/lib/python3.9/site-packages/mautrix_signal/commands/auth.py", line 180, in register
    username = await evt.bridge.signal.register(phone, voice=voice, captcha=captcha)
  File "/opt/yunohost/mautrix_signal/lib/python3.9/site-packages/mausignald/signald.py", line 160, in register
    resp = await self.request_v1("register", account=phone, voice=voice, captcha=captcha)
  File "/opt/yunohost/mautrix_signal/lib/python3.9/site-packages/mausignald/rpc.py", line 244, in request_v1
    return await self._request(command, expected_response=command, version="v1", **data)
  File "/opt/yunohost/mautrix_signal/lib/python3.9/site-packages/mausignald/rpc.py", line 238, in _request
    resp_type, resp_data = await self._raw_request(command, **data)
  File "/opt/yunohost/mautrix_signal/lib/python3.9/site-packages/mausignald/rpc.py", line 235, in _raw_request
    return await asyncio.shield(future)
mausignald.errors.InternalError: error registering with server
